name: Bug Report
description: Report a bug
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the Bug
      description: Description of the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: A list of steps to reproduce
      placeholder: |
        1. ...
        2. ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - OS: [windows, macos]
          - Browser: [chrome, safari]
          - Version: [99, 100, 101]
          - App Version: [1.0.0]
      value: |
        - OS:
        - Browser:
        - Version:
        - App Version:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Anything else to add? Like screenshots and other information about reproducing the bug
    validations:
      required: false
