name: Bump and Release

on:
  push:
    branches:
      - main

env:
  CI_GIT_TOKEN: ${{ secrets.CI_GIT_TOKEN }}

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip-release]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ env.CI_GIT_TOKEN }}

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: get major version
        if: "contains(github.event.head_commit.message, '[major]')"
        run: echo "RELEASE=major" >> $GITHUB_ENV

      - name: get minor version
        if: "contains(github.event.head_commit.message, '[minor]')"
        run: echo "RELEASE=minor" >> $GITHUB_ENV

      - run: yarn

      - name: run release-it
        run: yarn release ${{ env.RELEASE }} --ci
        env:
          GITHUB_TOKEN: ${{ env.CI_GIT_TOKEN }}
