name: QA - Build and Deploy as Azure Static App

on:
  push:
    branches:
      - main

jobs:
  release_and_bump:
    steps:
      - uses: ./.github/workflows/release_and_bump.yml

  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    environment: staging
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.QA_AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env: # Add environment variables here
          CI: false # set CI to 'false' in QA
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }} # Set in 'staging' environment: https://github.com/it-pebune/ani-research-web/settings/environments
          REACT_APP_WEB_BASE_URL: ${{ secrets.REACT_APP_WEB_BASE_URL }} # Set in 'staging' environment: https://github.com/it-pebune/ani-research-web/settings/environments
