name: PR - Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: yarn install
      - name: Run Prettier
        run: yarn format:check
      - name: Run ESLint
        run: yarn lint
