name: "Pull Request Labeler"

on:
  pull_request_target:
    types:
      - opened

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const current_branch = pr.head.ref;

            const branches = [ 'feature', 'fix', 'hotfix' ];

            let label = '';

            branches.forEach((branch) => {
              if (current_branch.startsWith(branch)) {
                label = branch;
              }
            });

            if (label != '') {
              await github.rest.issues.addLabels({
                issue_number: pr.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: [ label ]
              });
            }
