# Reusable workflow
name: Release and Bump

on:
  workflow_call:

jobs:
  release_and_bump:
    if: "!contains(github.event.head_commit.message, '[skip-release]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.IT_PEBUNE_BOT_ACCOUNT_TOKEN }}

      - name: git config
        run: |
          git config user.name "${{ secrets.IT_PEBUNE_BOT_ACCOUNT }}"
          git config user.email "${{ secrets.IT_PEBUNE_BOT_ACCOUNT }}@users.noreply.github.com"

      - name: get major version
        if: "contains(github.event.head_commit.message, '[major]')"
        run: echo "RELEASE=major" >> $GITHUB_ENV

      - name: get minor version
        if: "contains(github.event.head_commit.message, '[minor]')"
        run: echo "RELEASE=minor" >> $GITHUB_ENV

      - run: yarn install

      - name: run release-it
        run: yarn release ${{ env.RELEASE }} --ci
        env:
          GITHUB_TOKEN: ${{ secrets.IT_PEBUNE_BOT_ACCOUNT_TOKEN }}
